apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resultpodapp
      type: backend
  template:
    metadata:
      name: result-app-pod
      labels:
        name: resultpodapp
        type: backend
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80